language: python
matrix:
  include:
    - python: 3.6
      sudo: true
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - "pip install nose"
  - "pip install pycodestyle pydocstyle pyflakes"
  - "pip install coverage"
  - "pip install codacy-coverage"
  - "pip install collective.checkdocs Pygments"
  - "python setup.py install"
script:
  - nosetests --with-coverage --cover-package=plyara --cover-xml
  - pycodestyle --max-line-length=120 plyara/*.py
  - pycodestyle --max-line-length=120 setup.py
  - pydocstyle --ignore=D104 plyara/__init__.py
  - pydocstyle --ignore=D203,D205,D208,D209,D213,D300,D400,D401,D403,D406,D407,D413 plyara/core.py
  - pydocstyle --ignore=D203 plyara/exceptions.py
  - pydocstyle plyara/command_line.py
  - pydocstyle setup.py
  - pyflakes plyara/core.py
  - pyflakes plyara/exceptions.py
  - pyflakes plyara/command_line.py
  - pyflakes setup.py
  - python setup.py checkdocs
after_success:
  - python-codacy-coverage
