language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install nose"
  - "pip install coverage"
  - "pip install codacy-coverage"
  - "pip install collective.checkdocs"
  - "python setup.py install"
script:
  - nosetests --with-coverage --cover-package=plyara --cover-xml
  - python setup.py checkdocs
after_success:
  - python-codacy-coverage
